### ISSUE TITLE
JSON decode error for c3s-cordex data

### ISSUE THREAD

**Issue by ellesmith88** [roocs/dataset-issues#2]
Data with ds_id = `"c3s-cordex.output.EUR-11.IPSL.MOHC-HadGEM2-ES.rcp85.r1i1p1.IPSL-WRF381P.v1.day.tas.v20190212"` 
has error: `json.decoder.JSONDecodeError: Expecting value: line 60 column 20`
when scanning with character scanner.

Edit: seems to be the case for other IPSL data

**Comment by agstephens** [comment]
Not sure if this will be relevant, but I had an issue where I did:
 1. Scan a ds_id
 2. Character is collected okay
 3. JSON file starts writing but only partially written due to a type error
 4. So you have a half-completed JSON character file
 5. And when you go to read it (to check if we need to re-scan) - then the JSON decoder fails
 6. Maybe create a unit test that makes one of these files and then asserts some good behaviour in response to trying to read it. Maybe the scanner should say: "CORRUPT JSON FILE FOUND: <path>"

**Comment by ellesmith88** [comment]
@agstephens Do you have the ds_id of the file you were scanning? Or was it the one above before the code was changed?

**Comment by agstephens** [comment]
@ellesmith88 , it was one that got fixed when we made a change to the character extraction. 
What you could do in this test is:
 1. Create a _bad_ JSON file by writing to a text file `{  "something": [1, 2` 
 2. Then try to read it, you should get the same JSON decoding error.
 3. Then assert the code responds appropriately.

**Comment by ellesmith88** [comment]
@agstephens 
I made a PR with a test. 
Thought something like this in the `scan_dataset` function would solve this. 


```
try:
    # if json file exists get mode
    data = json.load(open(outputs["json"]))
    mode = data["scan_metadata"]["mode"]
    if mode == 'quick':
        print(f'[INFO] Already ran for: {ds_id} in quick mode')
        return True
    if mode == 'full':
        check = _check_for_min_max(outputs["json"])
        if check:
            print(f'[INFO] Already ran for: {ds_id} in full mode')
            return True
except json.decoder.JSONDecodeError as exc:
    os.remove(outputs["json"])
    print(f'[INFO] Corrupt JSON file. Deleting and re-running.')
```



What do you think?

**Comment by agstephens** [comment]
@ellesmith88 looks good!

**Comment by agstephens** [comment]
Solved in code. Closing.
